# products = [
# 	{
# 		_id: '1',
# 		name: 'Airpods Wireless (3rd generation)',
# 		image: '/images/airpods.png',
# 		description:
# 			'Connect effortlessly, automatically switch between all your devices, and share audio easily.',
# 		brand: 'Apple',
# 		category: 'Electronics',
# 		price: 179.0,
# 		countInStock: 10,
# 		rating: 4.5,
# 		numReviews: 12,
# 	},
# 	{
# 		_id: '2',
# 		name: 'iPhone 13 Pro 1TB Memory',
# 		image: '/images/ip13.png',
# 		description:
# 			'Most advanced dual‑camera system ever.A lightning-fast chip that leaves the competition behind.Ceramic shield front, Glass back and aluminum design.',
# 		brand: 'Apple',
# 		category: 'Electronics',
# 		price: 999.99,
# 		countInStock: 0,
# 		rating: 4.0,
# 		numReviews: 8,
# 	},
# 	{
# 		_id: '3',
# 		name: 'Apple Watch (PRODUCT)RED Aluminum Case with Braided Solo Loop',
# 		image: '/images/iwatch.png',
# 		description:
# 			'The aluminum case is lightweight and made from 100 percent recycled aerospace-grade alloy.The Braided Solo Loop is made from recycled yarn and silicone threads for an ultracomfortable, stretchable design with no clasps or buckles.',
# 		brand: 'Apple',
# 		category: 'Electronics',
# 		price: 449.0,
# 		countInStock: 5,
# 		rating: 3,
# 		numReviews: 12,
# 	},
# 	{
# 		_id: '4',
# 		name: 'MacBook Pro',
# 		image: '/images/mbp1.png',
# 		description:
# 			'10-Core CPU, 16-Core GPU, 16GB Unified Memory, 512GB SSD Storage¹, 16-core Neural Engine, 16-inch Liquid Retina XDR display, Three Thunderbolt 4 ports, HDMI port, SDXC card slot, MagSafe 3 port, Magic Keyboard with Touch ID, Force Touch trackpad, 140W USB-C Power Adapter.',
# 		brand: 'Apple',
# 		category: 'Electronics',
# 		price: '2,499.99',
# 		countInStock: 11,
# 		rating: 5,
# 		numReviews: 12,
# 	},
# 	{
# 		_id: '5',
# 		name: 'IPAD PRO',
# 		image: '/images/ipp1.png',
# 		description:
# 			'iPad is so versatile, it’s more than up to any task. Whether you’re working on a project, expressing your creativity, or playing an immersive game, iPad is a fun and powerful way to get it done. Here are just a few of the countless things you can do with iPad.',
# 		brand: 'Apple',
# 		category: 'Electronics',
# 		price: 799.99,
# 		countInStock: 7,
# 		rating: 3.5,
# 		numReviews: 10,
# 	},
# 	{
# 		_id: '6',
# 		name: 'Louis Vuitton - BELLA - EXCLUSIVE PRELAUNCH',
# 		image: '/images/lvbag.png',
# 		description:
# 			'The Bella bucket bag is made from Mahina calf leather with a metallized aspect. The bag’s small size, perforated Monogram pattern, and attached round coin purse make it modern, desirable and trendy.',
# 		brand: 'Louis Vuitton',
# 		category: 'Apparel',
# 		price: '3,800.0',
# 		countInStock: 6,
# 		rating: 4,
# 		numReviews: 12,
# 	},
# 	{
# 		_id: '7',
# 		name: 'Louis Vuitton - ULTIMATE ANKLE BOOT',
# 		image: '/images/lvboot.png',
# 		description:
# 			'Crafted from velvety suede calf leather, the Ultimate ankle boot is a feminine design which contrasts a sleek upper with an embellished heel. ',
# 		brand: 'Louis Vuitton',
# 		category: 'Electronics',
# 		price: '1,850.0',
# 		countInStock: 5,
# 		rating: 4,
# 		numReviews: 12,
# 	},
# 	{
# 		_id: '8',
# 		name: 'Louis Vuitton - HORIZON SOFT DUFFLE 55',
# 		image: '/images/lvduffle.png',
# 		description:
# 			'Designed in collaboration with famed industrial designer Marc Newson, the Horizon Soft Duffel 55 is a rolling duffel bag, made from Damier Graphite coated canvas. Ultra-modern and very practical, it offers an extra-large capacity in a cabin-size bag, thanks to its external trolley system. Its wide U opening and double-zip closing system provide quick access to what’s inside. ',
# 		brand: 'Louis Vuitton',
# 		category: 'Electronics',
# 		price: '2,950.0',
# 		countInStock: 5,
# 		rating: 4,
# 		numReviews: 12,
# 	},
# ];


